name: Deploy

on:
  push:
    branches:
      - main
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Navigate to repo
      run: cd $GITHUB_WORKSPACE
    - name: Install deps
      run: npm install
    - name: Publish
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}